### ISSUE TITLE
启动项目报错Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by chinaitman** [wechatpay-apiv3/wechatpay-java#298]
### 错误描述

springboot2.7.7
启动项目后报错如下：
Caused by: java.lang.NoClassDefFoundError: Lcom/wechat/pay/java/service/merchantexclusivecoupon/MerchantExclusiveCouponService;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:738)
	... 37 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.wechat.pay.java.service.merchantexclusivecoupon.MerchantExclusiveCouponService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 41 common frames omitted

### 重现bug的步骤

启动springboot项目就报错找不到类

### 预期行为

是什么原因会出现ClassNotFoundException异常

### 操作系统

windows11

### Java 版本

Java 8

### wechatpay-java 版本

0.2.14

**Comment by zhk121314** [comment]
解决了吗
