### ISSUE TITLE
接入微信支付sdk， 在RSAAutoCertificateConfig build 阶段报证书不存在， 使用postman调试工具调试是可以的

### ISSUE THREAD

**Issue by SpringZch** [wechatpay-apiv3/wechatpay-java#303]
### 错误描述

Exception in thread "main" com.wechat.pay.java.core.exception.ServiceException: Wrong HttpStatusCode[404]
httpResponseBody[{"code":"RESOURCE_NOT_EXISTS","message":"证书不存在"}]	HttpRequest[{"http_method":"GET","url":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","uri":"https://api.mch.weixin.qq.com/v3/certificates?algorithm_type=RSA","headers":{商户信息}"","Accept":" */*","User-Agent":"WechatPay-Java/0.2.14 (Mac OS X/10.16) Java/1.8.0_45 Credential/WechatPay2Credential Validator/ okhttp3/null","Content-Type":"application/json"}}}]
	at com.wechat.pay.java.core.http.AbstractHttpClient.validateResponse(AbstractHttpClient.java:74)
	at com.wechat.pay.java.core.http.AbstractHttpClient.execute(AbstractHttpClient.java:45)
	at com.wechat.pay.java.core.certificate.CertificateDownloader.download(CertificateDownloader.java:82)
	at com.wechat.pay.java.core.certificate.AutoCertificateService.lambda$register$0(AutoCertificateService.java:66)
	at com.wechat.pay.java.core.certificate.AutoCertificateService$$Lambda$5/1046665075.run(Unknown Source)
	at com.wechat.pay.java.core.certificate.AutoCertificateService.register(AutoCertificateService.java:72)
	at com.wechat.pay.java.core.certificate.RSAAutoCertificateProvider.<init>(RSAAutoCertificateProvider.java:40)
	at com.wechat.pay.java.core.certificate.RSAAutoCertificateProvider.<init>(RSAAutoCertificateProvider.java:19)
	at com.wechat.pay.java.core.certificate.RSAAutoCertificateProvider$Builder.build(RSAAutoCertificateProvider.java:134)

### 重现bug的步骤

使用 AppServiceExtensionExample 即可复现， 其他的example 也是这个问题

### 预期行为

期望能成功配置并实现下单、查单接口

### 操作系统

macOS

### Java 版本

java 8 

### wechatpay-java 版本

0.2.14

### 其他信息

public class AppServiceExtensionExample {
    /** 商户号 */
    public static String merchantId = "XXX";

    /** 商户API私钥路径 */
    public static String privateKeyPath = "/Users/user/Documents/XX/ce/apiclient_key.pem";

    /** 商户证书序列号 */
    public static String merchantSerialNumber = "XXXXX";

    /** 商户APIV3密钥 */
    public static String apiV3Key = "XXXXX";

    public static AppServiceExtension service;

    public static void main(String[] args) throws IOException {
/*
        ClassPathResource classPathResource = new ClassPathResource("wechat/apiclient_key.pem");
        String privateKeyString = new BufferedReader(new InputStreamReader(classPathResource.getInputStream()))
                .lines().collect(Collectors.joining(System.lineSeparator()));

        PrivateKey privateKey = PemUtil.loadPrivateKeyFromString(privateKeyString);
*/

        // 初始化商户配置
        Config config =
                new RSAAutoCertificateConfig.Builder()
                        .merchantId(merchantId)
                        //.privateKey(privateKey)
                        // 使用 com.wechat.pay.java.core.util 中的函数从本地文件中加载商户私钥，商户私钥会用来生成请求的签名
                        .privateKeyFromPath(privateKeyPath)
                        .merchantSerialNumber(merchantSerialNumber)
                        .apiV3Key(apiV3Key)
                        .build();
        // 初始化服务
        service = new AppServiceExtension.Builder().config(config).build();
        try {
            // ... 调用接口
            PrepayWithRequestPaymentResponse response = prepayWithRequestPayment();
            System.out.println(response);
        } catch (HttpException e) { // 发送HTTP请求失败
            // 调用e.getHttpRequest()获取请求打印日志或上报监控，更多方法见HttpException定义
        } catch (ServiceException e) { // 服务返回状态小于200或大于等于300，例如500
            // 调用e.getResponseBody()获取返回体打印日志或上报监控，更多方法见ServiceException定义
        } catch (MalformedMessageException e) { // 服务返回成功，返回体类型不合法，或者解析返回体失败
            // 调用e.getMessage()获取信息打印日志或上报监控，更多方法见MalformedMessageException定义
        }
    }

**Comment by aohanhe** [comment]
我也遇到相同的问题，仔细检查商户号，再次申请证书以及密钥都遇相同的近回错误
