### ISSUE TITLE
自动更新微信支付平台证书的问题

### ISSUE THREAD

**Issue by Rainron** [wechatpay-apiv3/wechatpay-java#325]
### 错误描述

Config config =
    new RSAAutoCertificateConfig.Builder()
        .merchantId(merchantId)
        .privateKeyFromPath(privateKeyPath)
        .merchantSerialNumber(merchantSerialNumber)
        .apiV3Key(apiV3Key)
        .build();

初始化提示---无可用的平台证书，请在商户平台-API安全申请使用微信支付公钥。

### 重现bug的步骤

根据README.md文档步骤操作

### 预期行为

希望有一个完整的引用测试demo

### 操作系统

win10

### Java 版本

17

### wechatpay-java 版本

0.2.15

**Comment by wswdavid** [comment]
微信支付公钥说明 https://pay.weixin.qq.com/doc/v3/merchant/4012153196

SDK初始化参考公钥部分的说明
<img width="986" alt="image" src="https://github.com/user-attachments/assets/194a4105-b505-4d97-bd07-9b0cb7ee380e" />

**Comment by Rainron** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fanrujiang** [comment]
解决了吗 求分享

**Comment by Rainron** [comment]
> 解决了吗 求分享

按照上面答复的使用平台公钥进行初始化，我不明白的是证书模式为什么报错又不提示，文档又不更新？我也是第一次对接微信支付，相比之下支付宝对接更好

**Comment by fanrujiang** [comment]
> > 解决了吗 求分享
> 
> 按照上面答复的使用平台公钥进行初始化，我不明白的是证书模式为什么报错又不提示，文档又不更新？我也是第一次对接微信支付，相比之下支付宝对接更好

是的，官方文档误导开发者，微信支付的文档简直是一坨 💩

**Comment by dahaiwugui** [comment]
我的一直报这个错，配置都重新生成了，私钥和ID都是粘贴的
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1395)
        at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:406)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
        at com.wechat.pay.java.core.cipher.AbstractAeadCipher.decrypt(AbstractAeadCipher.java:78)

**Comment by it-ll** [comment]
最后怎么解决的
