### ISSUE TITLE
validateResponse 异常

### ISSUE THREAD

**Issue by chengling235** [wechatpay-apiv3/wechatpay-java#81]
### 错误描述

 Validate response failed,the WechatPay signature is incorrect.

### 重现bug的步骤

Exception in thread "main" com.wechat.pay.java.core.exception.ValidationException: Validate response failed,the WechatPay signature is incorrect.
	at com.wechat.pay.java.core.http.AbstractHttpClient.validateResponse(AbstractHttpClient.java:70)
	at com.wechat.pay.java.core.http.AbstractHttpClient.execute(AbstractHttpClient.java:43)
	at com.wechat.pay.java.service.payments.jsapi.JsapiService.prepay(JsapiService.java:162)
	at com.mineway.crm.zx.pay.WxPay.main(WxPay.java:50)
Disconnected from the target VM, address: '127.0.0.1:62376', transport: 'socket'

### 预期行为

Exception in thread "main" com.wechat.pay.java.core.exception.ValidationException: Validate response failed,the WechatPay signature is incorrect.
	at com.wechat.pay.java.core.http.AbstractHttpClient.validateResponse(AbstractHttpClient.java:70)
	at com.wechat.pay.java.core.http.AbstractHttpClient.execute(AbstractHttpClient.java:43)
	at com.wechat.pay.java.service.payments.jsapi.JsapiService.prepay(JsapiService.java:162)
	at com.mineway.crm.zx.pay.WxPay.main(WxPay.java:50)
Disconnected from the target VM, address: '127.0.0.1:62376', transport: 'socket'

### 操作系统

macos

### Java 版本

8

### wechatpay-java 版本

0.2.1

**Comment by xy-peng** [comment]
请看下是否使用的微信支付平台证书？

**Comment by lianup** [comment]
你需要设置的是微信支付平台证书，你用的是商户证书。

首次下载平台证书可使用[微信支付 APIv3 平台证书下载工具](https://github.com/wechatpay-apiv3/CertificateDownloader)。

**Comment by chengling235** [comment]
@lianup 现在好了，谢谢
