### ISSUE TITLE
java.lang.IllegalArgumentException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input

### ISSUE THREAD

**Issue by chengling235** [wechatpay-apiv3/wechatpay-java#85]
### 错误描述

java.lang.IllegalArgumentException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromStream(PemUtil.java:114)
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromString(PemUtil.java:172)
	at com.wechat.pay.java.core.notification.RSANotificationConfig$Builder.certificates(RSANotificationConfig.java:64)
	at com.mineway.crm.service.pay.WxPayService.getDecryptObject(WxPayService.java:139)
	at com.mineway.crm.service.impl.OrderServiceImpl.payNotify(OrderServiceImpl.java:276)

### 重现bug的步骤

java.lang.IllegalArgumentException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromStream(PemUtil.java:114)
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromString(PemUtil.java:172)
	at com.wechat.pay.java.core.notification.RSANotificationConfig$Builder.certificates(RSANotificationConfig.java:64)
	at com.mineway.crm.service.pay.WxPayService.getDecryptObject(WxPayService.java:139)
	at com.mineway.crm.service.impl.OrderServiceImpl.payNotify(OrderServiceImpl.java:276)

### 预期行为

java.lang.IllegalArgumentException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromStream(PemUtil.java:114)
	at com.wechat.pay.java.core.util.PemUtil.loadX509FromString(PemUtil.java:172)
	at com.wechat.pay.java.core.notification.RSANotificationConfig$Builder.certificates(RSANotificationConfig.java:64)
	at com.mineway.crm.service.pay.WxPayService.getDecryptObject(WxPayService.java:139)
	at com.mineway.crm.service.impl.OrderServiceImpl.payNotify(OrderServiceImpl.java:276)

### 操作系统

macOS

### Java 版本

Java8

### wechatpay-java 版本

0.2.2

**Comment by chengling235** [comment]
是传平台证书序列号吗
